-- MySQL Script generated by MySQL Workbench
-- Mon Apr 24 16:54:19 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema CC
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema CC
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `CC` DEFAULT CHARACTER SET utf8 ;
USE `CC` ;

-- -----------------------------------------------------
-- Table `CC`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CC`.`Usuario` (
  `idUsuario` INT NOT NULL,
  `nombre` VARCHAR(30) NULL,
  `password` VARCHAR(20) NULL,
  `email` VARCHAR(30) NULL,
  `icono` VARCHAR(45) NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CC`.`Evento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CC`.`Evento` (
  `idEvento` INT NOT NULL,
  `nombre` VARCHAR(30) NULL,
  `divisa` VARCHAR(9) NULL,
  PRIMARY KEY (`idEvento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CC`.`Gasto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CC`.`Gasto` (
  `idGasto` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `precio` INT NULL,
  `Usuario_idUsuario` INT NOT NULL,
  `Evento_idEvento` INT NOT NULL,
  PRIMARY KEY (`idGasto`, `Usuario_idUsuario`, `Evento_idEvento`),
  INDEX `fk_Gasto_Usuario1_idx` (`Usuario_idUsuario` ASC),
  INDEX `fk_Gasto_Evento1_idx` (`Evento_idEvento` ASC),
  CONSTRAINT `fk_Gasto_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `CC`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Gasto_Evento1`
    FOREIGN KEY (`Evento_idEvento`)
    REFERENCES `CC`.`Evento` (`idEvento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CC`.`Usuario_has_Evento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CC`.`Usuario_has_Evento` (
  `Usuario_idUsuario` INT NOT NULL,
  `Evento_idEvento` INT NOT NULL,
  PRIMARY KEY (`Usuario_idUsuario`, `Evento_idEvento`),
  INDEX `fk_Usuario_has_Evento_Evento1_idx` (`Evento_idEvento` ASC),
  INDEX `fk_Usuario_has_Evento_Usuario_idx` (`Usuario_idUsuario` ASC),
  CONSTRAINT `fk_Usuario_has_Evento_Usuario`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `CC`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_has_Evento_Evento1`
    FOREIGN KEY (`Evento_idEvento`)
    REFERENCES `CC`.`Evento` (`idEvento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CC`.`Usuario_has_Gasto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CC`.`Usuario_has_Gasto` (
  `Usuario_idUsuario` INT NOT NULL,
  `Gasto_idGasto` INT NOT NULL,
  PRIMARY KEY (`Usuario_idUsuario`, `Gasto_idGasto`),
  INDEX `fk_Usuario_has_Gasto_Gasto1_idx` (`Gasto_idGasto` ASC),
  INDEX `fk_Usuario_has_Gasto_Usuario1_idx` (`Usuario_idUsuario` ASC),
  CONSTRAINT `fk_Usuario_has_Gasto_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `CC`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_has_Gasto_Gasto1`
    FOREIGN KEY (`Gasto_idGasto`)
    REFERENCES `CC`.`Gasto` (`idGasto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
