package tad.grupo7.ccamistadeslargas.modelo;
// Generated 24-abr-2017 17:13:21 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Evento generated by hbm2java
 */
public class Evento  implements java.io.Serializable {


     private int idEvento;
     private String nombre;
     private String divisa;
     private Set usuarios = new HashSet(0);
     private Set gastos = new HashSet(0);

    public Evento() {
    }

	
    public Evento(int idEvento) {
        this.idEvento = idEvento;
    }
    public Evento(int idEvento, String nombre, String divisa, Set usuarios, Set gastos) {
       this.idEvento = idEvento;
       this.nombre = nombre;
       this.divisa = divisa;
       this.usuarios = usuarios;
       this.gastos = gastos;
    }
   
    public int getIdEvento() {
        return this.idEvento;
    }
    
    public void setIdEvento(int idEvento) {
        this.idEvento = idEvento;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDivisa() {
        return this.divisa;
    }
    
    public void setDivisa(String divisa) {
        this.divisa = divisa;
    }
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }
    public Set getGastos() {
        return this.gastos;
    }
    
    public void setGastos(Set gastos) {
        this.gastos = gastos;
    }

    public String[] getArray(){
        return new String[]{getNombre(),getDivisa()};
    }
}


