package modelo;
// Generated 24-abr-2017 17:13:21 by Hibernate Tools 4.3.1



/**
 * GastoId generated by hbm2java
 */
public class GastoId  implements java.io.Serializable {


     private int idGasto;
     private int usuarioIdUsuario;
     private int eventoIdEvento;

    public GastoId() {
    }

    public GastoId(int idGasto, int usuarioIdUsuario, int eventoIdEvento) {
       this.idGasto = idGasto;
       this.usuarioIdUsuario = usuarioIdUsuario;
       this.eventoIdEvento = eventoIdEvento;
    }
   
    public int getIdGasto() {
        return this.idGasto;
    }
    
    public void setIdGasto(int idGasto) {
        this.idGasto = idGasto;
    }
    public int getUsuarioIdUsuario() {
        return this.usuarioIdUsuario;
    }
    
    public void setUsuarioIdUsuario(int usuarioIdUsuario) {
        this.usuarioIdUsuario = usuarioIdUsuario;
    }
    public int getEventoIdEvento() {
        return this.eventoIdEvento;
    }
    
    public void setEventoIdEvento(int eventoIdEvento) {
        this.eventoIdEvento = eventoIdEvento;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof GastoId) ) return false;
		 GastoId castOther = ( GastoId ) other; 
         
		 return (this.getIdGasto()==castOther.getIdGasto())
 && (this.getUsuarioIdUsuario()==castOther.getUsuarioIdUsuario())
 && (this.getEventoIdEvento()==castOther.getEventoIdEvento());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdGasto();
         result = 37 * result + this.getUsuarioIdUsuario();
         result = 37 * result + this.getEventoIdEvento();
         return result;
   }   


}


