package tad.grupo7.ccamistadeslargas.modelo;
// Generated 24-abr-2017 17:13:21 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Gasto generated by hbm2java
 */
public class Gasto  implements java.io.Serializable {


     private GastoId id;
     private Evento evento;
     private Usuario usuario;
     private String nombre;
     private Integer precio;
     private Set usuarios = new HashSet(0);

    public Gasto() {
    }

	
    public Gasto(GastoId id, Evento evento, Usuario usuario) {
        this.id = id;
        this.evento = evento;
        this.usuario = usuario;
    }
    public Gasto(GastoId id, Evento evento, Usuario usuario, String nombre, Integer precio, Set usuarios) {
       this.id = id;
       this.evento = evento;
       this.usuario = usuario;
       this.nombre = nombre;
       this.precio = precio;
       this.usuarios = usuarios;
    }
   
    public GastoId getId() {
        return this.id;
    }
    
    public void setId(GastoId id) {
        this.id = id;
    }
    public Evento getEvento() {
        return this.evento;
    }
    
    public void setEvento(Evento evento) {
        this.evento = evento;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Integer getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(Integer precio) {
        this.precio = precio;
    }
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }




}


