package tad.grupo7.ccamistadeslargas.modelo;
// Generated 24-abr-2017 17:13:21 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private int idUsuario;
     private String nombre;
     private String password;
     private String email;
     private String icono;
     private Set gastos = new HashSet(0);
     private Set eventos = new HashSet(0);
     private Set gastos_1 = new HashSet(0);

    public Usuario() {
    }

	
    public Usuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }
    public Usuario(int idUsuario, String nombre, String password, String email, String icono, Set gastos, Set eventos, Set gastos_1) {
       this.idUsuario = idUsuario;
       this.nombre = nombre;
       this.password = password;
       this.email = email;
       this.icono = icono;
       this.gastos = gastos;
       this.eventos = eventos;
       this.gastos_1 = gastos_1;
    }
   
    public int getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getIcono() {
        return this.icono;
    }
    
    public void setIcono(String icono) {
        this.icono = icono;
    }
    public Set getGastos() {
        return this.gastos;
    }
    
    public void setGastos(Set gastos) {
        this.gastos = gastos;
    }
    public Set getEventos() {
        return this.eventos;
    }
    
    public void setEventos(Set eventos) {
        this.eventos = eventos;
    }
    public Set getGastos_1() {
        return this.gastos_1;
    }
    
    public void setGastos_1(Set gastos_1) {
        this.gastos_1 = gastos_1;
    }




}


